### ISSUE TITLE
How to update to a new release

### ISSUE THREAD

**Issue by Lod3** [BitCurator/bitcurator-distro-installer#3]
Hi,

I would like to update to the new release (2.2.18.), I am currently on 2.2.16. 
Can I just run ```sudo ./install.sh -u username``` to update? 
Or do I need to do a fresh install?

**Comment by kamwoods** [comment]
A fresh install is safest. Improving the state management in the installer
to support clean upgrades is on the to-do list for the maintainers.

**Comment by Lod3** [comment]
I was afraid this would be the answer, but thank you nonetheless. 
Is there a public to-do list we can use to see what features are coming next?

**Comment by kamwoods** [comment]
The BCC has a Jira instance for bug tracking and suggested improvements (
https://confluence.educopia.org/plugins/servlet/mobile?contentId=44138740#content/view/44138740),
although I'm not sure how up to date it is right now.
